window.LB_TRIVIA = [
  {q:'Botanically speaking, what is a banana?',c:['A berry','A nut wearing pajamas','A vegetable','A drupe'],a:0,f:'Bananas are berries. Strawberries are not. Botany enjoys conflict.'},
  {q:'How many hearts does an octopus bring to a breakup?',c:['One','Two','Three','Eight'],a:2,f:'Three hearts, zero interest in your relationship advice.'},
  {q:'Which animal produces cube-shaped droppings?',c:['Wombat','Accountant','Capybara','Yak'],a:0,f:'Wombats make cubes. Nature invented stackable poop.'},
  {q:'Scotland chose which creature as its national animal?',c:['Highland cow','Unicorn','Nessie','Haggis'],a:1,f:'The unicorn. Scotland refused to let reality limit branding.'},
  {q:'What is the dot above a lowercase i or j called?',c:['A specklet','A tittle','A jotter','A glyph wart'],a:1,f:'It is a tittle. Please use this power responsibly.'},
  {q:'Which letter appears in no official U.S. state name?',c:['J','Q','X','Z'],a:1,f:'Q has been formally rejected by all fifty states.'},
  {q:'The shortest recorded war, lasting under an hour in 1896, involved Britain and…?',c:['Zanzibar','Iceland','Liechtenstein','A very angry pigeon'],a:0,f:'The Anglo-Zanzibar War lasted roughly 38–45 minutes.'},
  {q:'The ashes of Pringles can designer Fred Baur were buried in what?',c:['A Pringles can','A potato field','A golden tube','His desk drawer'],a:0,f:'He got the burial container exactly right on the first try.'},
  {q:'Why can the Eiffel Tower become taller during summer?',c:['Tourist pressure','Thermal expansion','Seasonal confidence','Birds lift it'],a:1,f:'Heat expands the iron, adding several centimeters.'},
  {q:'What replaces upper front incisors in a cow?',c:['Tiny backup teeth','A dental pad','Nothing but optimism','A cartilage zipper'],a:1,f:'Cows press grass against a tough dental pad.'},
  {q:'Which appeared on Earth first?',c:['Trees','Sharks','Dinosaurs','Monday meetings'],a:1,f:'Sharks predate trees by tens of millions of years.'},
  {q:'Cleopatra lived closer in time to which event than to the building of the Great Pyramid?',c:['The Moon landing','The fall of Troy','The invention of paper','The first sandwich'],a:0,f:'Ancient Egypt lasted long enough to make “ancient” confusing.'},
  {q:'Which institution is older than the Aztec Empire?',c:['Oxford University','The Louvre','Harvard University','The DMV'],a:0,f:'Teaching occurred at Oxford centuries before the Aztec Empire formed.'},
  {q:'Nintendo was founded in which century?',c:['17th','18th','19th','20th'],a:2,f:'Nintendo began in 1889 making playing cards.'},
  {q:'The first famous webcam watched what critically important object?',c:['A coffee pot','A server rack','A sleeping cat','The office door'],a:0,f:'Cambridge researchers monitored the Trojan Room coffee pot.'},
  {q:'The famous 1947 “computer bug” was literally what?',c:['A moth','A beetle','A spider','An unpaid intern'],a:0,f:'A moth was taped into the Harvard Mark II logbook.'},
  {q:'Python, the programming language, was named after what?',c:['The snake','Monty Python','A Greek oracle','A developer’s pet'],a:1,f:'Guido van Rossum chose Monty Python, not the reptile.'},
  {q:'What does CAPTCHA begin with?',c:['Completely Automated Public Turing test','Computerized Anti-Pirate Test','Confusing All People Through Chaotic Answers','Certified Access Protocol'],a:0,f:'The full acronym is somehow more exhausting than the traffic lights.'},
  {q:'What is the main job of DNS?',c:['Translate names into IP addresses','Clean browser history','Detect nonsense sentences','Make Wi-Fi moodier'],a:0,f:'DNS is the internet’s contact list.'},
  {q:'HTTP status code 418 says the server is what?',c:['A teapot','On fire','Too tired','British'],a:0,f:'418 “I’m a teapot” began as an April Fools’ joke.'},
  {q:'What is the Linux mascot called?',c:['Tux','Linus Jr.','Kernel Sanders','sudo'],a:0,f:'Tux is a penguin with excellent root privileges.'},
  {q:'The word “robot” comes from a Czech word associated with…?',c:['Forced labor','Metal','Thinking','Tiny dance moves'],a:0,f:'Robota refers to forced labor or drudgery. Cheerful origin.'},
  {q:'Which chemical element uses the symbol W?',c:['Tungsten','Tantalum','Tin','Wolframium Jr.'],a:0,f:'W comes from wolfram, an older name for tungsten.'},
  {q:'Which element is named after the Norse god of thunder?',c:['Thorium','Osmium','Vanadium','Bonkium'],a:0,f:'Thorium was named after Thor. It does not include a hammer.'},
  {q:'Which metal can melt in a warm human hand?',c:['Gallium','Iron','Titanium','Aluminum'],a:0,f:'Gallium melts near 29.8°C. Do not make a spoon unless you enjoy betrayal.'},
  {q:'At water’s triple point, solid, liquid and vapor can coexist at approximately…?',c:['0.01°C','10°C','-40°C','100°C'],a:0,f:'The triple point of water is 0.01°C at a specific pressure.'},
  {q:'Which mammals are capable of true sustained flight?',c:['Bats','Flying squirrels','Sugar gliders','Overdue passengers'],a:0,f:'Gliders glide. Bats actually fly.'},
  {q:'Where is a male platypus’s venom-delivering spur?',c:['Hind leg','Bill','Tail','Tiny utility belt'],a:0,f:'Males have venomous ankle spurs, because the platypus needed another feature.'},
  {q:'Which jellyfish can revert to an earlier life stage and potentially repeat its life cycle?',c:['Turritopsis dohrnii','Moon jelly','Box jellyfish','Benjamin Buttonfish'],a:0,f:'Turritopsis dohrnii is nicknamed the immortal jellyfish.'},
  {q:'An axolotl is famous for regenerating what?',c:['Limbs and parts of major organs','Only its tail','Its entire personality','Teeth only'],a:0,f:'Axolotls can regenerate limbs and tissues including parts of the heart and spinal cord.'},
  {q:'A narwhal’s tusk is actually an enlarged…?',c:['Tooth','Horn','Nose bone','Frozen noodle'],a:0,f:'It is a long sensory tooth, usually an upper-left canine.'},
  {q:'Which animal has fingerprints remarkably similar to humans?',c:['Koala','Panda','Otter','Pickpocket crab'],a:0,f:'Koala fingerprints can look surprisingly human.'},
  {q:'Which birds are known to recognize and remember individual human faces?',c:['Crows','Ostriches','Penguins','Rubber ducks'],a:0,f:'Crows remember faces and can share threat information.'},
  {q:'Which animal can hold its breath for around 40 minutes by slowing its heart rate?',c:['Sloth','Dolphin','Hippo','Competitive librarian'],a:0,f:'Sloths can outlast many dolphins in breath-holding.'},
  {q:'What is a traditional collective noun for ravens?',c:['An unkindness','A complaint','A goth convention','A parliament'],a:0,f:'An unkindness of ravens sounds judgmental before breakfast.'},
  {q:'What is a group of flamingos traditionally called?',c:['A flamboyance','A blush','A shrimp meeting','A sparkle'],a:0,f:'A flamboyance. Subtlety was unavailable.'},
  {q:'What is a traditional collective noun for hedgehogs?',c:['An array','A prickle','A spreadsheet','A hedge fund'],a:0,f:'An array of hedgehogs is both adorable and badly indexed.'},
  {q:'What is a traditional collective noun for owls?',c:['A parliament','A senate','A night shift','A wisdom'],a:0,f:'A parliament of owls has yet to pass meaningful mouse reform.'},
  {q:'What is a traditional collective noun for ferrets?',c:['A business','A burglary','A noodle pile','A mischief'],a:0,f:'A business of ferrets is almost certainly unlicensed.'},
  {q:'Which animal breathes through structures connected to its anus?',c:['Sea cucumber','Jellyfish','Electric eel','Corporate middle management'],a:0,f:'Sea cucumbers pump water through a cloaca into respiratory trees.'},
  {q:'Domestic cats generally cannot taste which basic taste?',c:['Sweetness','Saltiness','Bitterness','Umami'],a:0,f:'Cats lack a functional sweet taste receptor.'},
  {q:'Which animal is famous for rectangular pupils?',c:['Goat','Wolf','Elephant','Geometry teacher'],a:0,f:'Horizontal rectangular pupils give grazing animals a wide view.'},
  {q:'A sea star has neither a centralized brain nor…?',c:['Blood','A stomach','Tube feet','Regrets'],a:0,f:'Sea stars circulate seawater through a water vascular system instead of blood.'},
  {q:'Which lizard can squirt blood from its eyes as a defense?',c:['Horned lizard','Komodo dragon','Gecko','Drama dragon'],a:0,f:'Some horned lizards weaponize eye blood. Your move, predators.'},
  {q:'How many people are needed for the birthday paradox to exceed a 50% match probability?',c:['23','50','183','366'],a:0,f:'With 23 people, a shared birthday is already more likely than not.'},
  {q:'What is special about a Möbius strip?',c:['It has one continuous side','It has zero edges','It cannot be cut','It files its own taxes'],a:0,f:'A Möbius strip has one side and one boundary curve.'},
  {q:'Why is 1729 called the Hardy–Ramanujan number?',c:['It is the smallest sum of two positive cubes in two ways','It is prime','It predicts eclipses','It was Ramanujan’s PIN'],a:0,f:'1729 = 1³ + 12³ = 9³ + 10³.'},
  {q:'Which standard Roman numeral represents zero?',c:['There is no standard one','N','O','Z'],a:0,f:'Classical Roman numerals had no standard symbol for zero.'},
  {q:'A pangram is a sentence containing…?',c:['Every letter of an alphabet','Only palindromes','No repeated words','At least one pangolin'],a:0,f:'“The quick brown fox…” is the celebrity pangram.'},
  {q:'In The Hitchhiker’s Guide to the Galaxy, what is the Answer to Life, the Universe, and Everything?',c:['42','Tea','A towel','Mostly harmless'],a:0,f:'42. Unfortunately, the question remains underfunded.'}
];
