(() => {
  'use strict';
  const LB=window.LB3;if(!LB)return;
  const {Game,Rig,POSES,pick,rnd,chance,clamp,ctxRoundRect}=LB,TAU=Math.PI*2;
  const INK='#211922',PAPER='#f5ead2',SHADOW='#352939';

  const shade=(hex,n=-24)=>{if(!/^#[0-9a-f]{6}$/i.test(hex))return hex;const v=parseInt(hex.slice(1),16),r=clamp((v>>16)+n,0,255),g=clamp(((v>>8)&255)+n,0,255),b=clamp((v&255)+n,0,255);return`rgb(${r},${g},${b})`};
  const hash=s=>{let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const wobble=(seed,i,amount=2)=>{const x=Math.sin((seed+i*91.7)*.017)*43758.5453;return(x-Math.floor(x)-.5)*amount};
  function path(c,pts,fill,stroke=INK,lw=5,closed=true){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(closed)c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=lw;c.lineJoin='round';c.lineCap='round';c.stroke()}}
  function organic(c,pts,fill,stroke=INK,lw=5){c.beginPath();c.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2;c.quadraticCurveTo(a[0],a[1],mx,my)}c.quadraticCurveTo(pts.at(-1)[0],pts.at(-1)[1],pts[0][0],pts[0][1]);c.closePath();c.fillStyle=fill;c.fill();c.strokeStyle=stroke;c.lineWidth=lw;c.lineJoin='round';c.stroke()}
  function capsule(c,a,b,w,color,seed=1,front=true){const dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,w1=w*.55,w2=w*.43,j=wobble(seed,3,2);c.beginPath();c.moveTo(a.x+nx*w1,a.y+ny*w1);c.quadraticCurveTo((a.x+b.x)/2+nx*(w*.54+j),(a.y+b.y)/2+ny*(w*.54+j),b.x+nx*w2,b.y+ny*w2);c.quadraticCurveTo(b.x+dx/L*3,b.y+dy/L*3,b.x-nx*w2,b.y-ny*w2);c.quadraticCurveTo((a.x+b.x)/2-nx*(w*.45-j),(a.y+b.y)/2-ny*(w*.45-j),a.x-nx*w1,a.y-ny*w1);c.closePath();c.fillStyle=color;c.fill();c.strokeStyle=INK;c.lineWidth=5;c.lineJoin='round';c.stroke();if(front){c.strokeStyle='rgba(255,255,255,.18)';c.lineWidth=2;c.beginPath();c.moveTo(a.x+nx*w*.25,a.y+ny*w*.25);c.lineTo(b.x+nx*w*.18,b.y+ny*w*.18);c.stroke()}return b}
  function joint(start,len,ang){return{x:start.x+Math.cos(ang)*len,y:start.y+Math.sin(ang)*len}}
  function hand(c,x,y,ang,skin,size=1,grip=false){c.save();c.translate(x,y);c.rotate(ang);c.beginPath();c.moveTo(-7*size,-8*size);c.quadraticCurveTo(5*size,-13*size,11*size,-5*size);c.quadraticCurveTo(15*size,2*size,8*size,11*size);c.quadraticCurveTo(-3*size,14*size,-9*size,7*size);c.closePath();c.fillStyle=skin;c.fill();c.strokeStyle=INK;c.lineWidth=4;c.stroke();c.strokeStyle=shade(skin,-35);c.lineWidth=1.6;if(!grip){[-3,1,5].forEach((yy,i)=>{c.beginPath();c.moveTo(1,yy);c.lineTo(9-i*.6,yy+1);c.stroke()})}else{c.beginPath();c.arc(2,1,6,-1.2,1.5);c.stroke()}c.restore()}
  function shoe(c,x,y,ang,color='#292633',scale=1){c.save();c.translate(x,y);c.rotate(ang*.18);c.beginPath();c.moveTo(-10*scale,-8*scale);c.quadraticCurveTo(8*scale,-12*scale,23*scale,-3*scale);c.quadraticCurveTo(29*scale,5*scale,19*scale,10*scale);c.lineTo(-11*scale,9*scale);c.quadraticCurveTo(-16*scale,0,-10*scale,-8*scale);c.closePath();c.fillStyle=color;c.fill();c.strokeStyle=INK;c.lineWidth=5;c.stroke();c.strokeStyle=PAPER;c.lineWidth=2;c.beginPath();c.moveTo(-6*scale,4*scale);c.lineTo(22*scale,5*scale);c.moveTo(3*scale,-3*scale);c.lineTo(13*scale,0);c.stroke();c.restore()}
  function eye(c,x,y,w,h,look,color,tilt=0,blink=0){c.save();c.translate(x,y);c.rotate(tilt);c.beginPath();if(blink>.7){c.moveTo(-w,0);c.quadraticCurveTo(0,2,w,0)}else{c.moveTo(-w,0);c.quadraticCurveTo(0,-h,w,0);c.quadraticCurveTo(0,h*.9,-w,0);c.fillStyle='#fffaf0';c.fill()}c.strokeStyle=INK;c.lineWidth=3.5;c.stroke();if(blink<=.7){const px=clamp(look,-1,1)*w*.28;c.beginPath();c.ellipse(px,1,w*.38,h*.52,0,0,TAU);c.fillStyle=color;c.fill();c.strokeStyle=INK;c.lineWidth=2;c.stroke();c.beginPath();c.arc(px+1,1,w*.17,0,TAU);c.fillStyle=INK;c.fill();c.beginPath();c.arc(px+2,-1,1.5,0,TAU);c.fillStyle='white';c.fill()}c.restore()}

  Object.assign(POSES,{
    heavyHit:{...POSES.hit,bob:-6,lean:-.72,head:.55,uaL:.95,laL:.7,uaR:-.8,laR:-.6,thL:.42,shL:.3,thR:-.5,shR:-.35},
    stunned:{...POSES.idle,bob:8,lean:.14,head:-.28,uaL:.35,laL:.7,uaR:-.4,laR:-.65,thL:.12,shL:.08,thR:-.1,shR:-.06},
    victory:{...POSES.idle,bob:-5,lean:-.08,head:-.12,uaL:-2.35,laL:-2.5,uaR:-.75,laR:-.5,thL:.14,shL:.08,thR:-.15,shR:-.08},
    pickup:{...POSES.groundSlam,bob:13,lean:.78,head:-.25},interact:{...POSES.windup,lean:.42},knockdown:{...POSES.fall,lean:-1.32},defeat:{...POSES.dead}
  });

  const oldRigUpdate=Rig.prototype.update;
  Rig.prototype.update=function(dt,moving=0){oldRigUpdate.call(this,dt,moving);this.moving=moving;this.visualTime=(this.visualTime||0)+dt;this.look+=((this.lookTarget||0)-this.look)*Math.min(1,dt*4)};

  Rig.prototype.draw=function(c){
    const p=this.pose||POSES.idle,b=this.build||1,seed=this.visualSeed||(this.visualSeed=hash([this.head,this.hair,this.outfit,this.face,this.presentation].join('|'))),t=this.visualTime||0,breath=Math.sin(t*3.1+seed%9),idle=/idle|guard/.test(this.state),squash=/hit|heavyHit|fall|dead|defeat/.test(this.state),stretch=/punchImpact|kickHead|kickBody|weaponHead|weaponBody|supermanImpact/.test(this.state);
    c.save();c.translate(this.x,this.y+4);c.globalAlpha=.25;c.fillStyle='#21151f';c.beginPath();c.ellipse(0,0,46*this.scale*b*(squash?1.35:1),12*this.scale*(squash?.72:1),0,0,TAU);c.fill();c.restore();
    c.save();c.translate(this.x,this.y+p.bob+(idle?breath*1.5:0));c.scale(this.dir*this.scale*(stretch?1.035:squash?1.07:1),this.scale*(stretch?.975:squash?.95:1));c.rotate(p.lean+(idle?Math.sin(t*1.3+seed)*.012:0));
    const skin=this.flash>0?'#fff8df':this.skin,skinShade=shade(this.skin,-26),torsoTop=-127,hipY=-59,shoulderY=-119,neckY=-139,legColor=this.bottom==='leggings'?shade(this.outfit,-30):this.bottom==='skirt'?shade(this.outfit,-25):'#3f4658',shoeColor=this.shoeColor||(this.shoeColor=pick(['#292633','#432d3a','#25394c']));
    this.drawBackHair(c,0,-178,seed);
    const hipL={x:-16*b,y:hipY},hipR={x:16*b,y:hipY},shL={x:-25*b,y:shoulderY},shR={x:25*b,y:shoulderY};
    if(!this.detached.legL)this.drawLeg(c,hipL,p.thL,p.shL,legColor,skin,shoeColor,seed+11,false);
    if(!this.detached.armL)this.drawArm(c,shL,p.uaL,p.laL,skin,seed+21,false,false);
    this.drawTorso(c,torsoTop,hipY,b,seed,breath);
    if(!this.detached.legR)this.drawLeg(c,hipR,p.thR,p.shR,shade(legColor,-10),skin,shoeColor,seed+31,true);
    if(!this.detached.armR){const h=this.drawArm(c,shR,p.uaR,p.laR,skin,seed+41,true,!!(this.weapon&&this.weapon.kind!=='fist'));if(this.weapon&&this.weapon.kind!=='fist')this.drawWeapon(c,h.x,h.y,p.laR+Math.PI*1.5)}
    if(!this.detached.head){this.drawNeck(c,neckY,skin,skinShade);this.drawCartoonHead(c,0,-174+p.head*9,skin,seed)}
    if(this.smear>0)this.drawInkSmear(c);this.drawInjuries(c);c.restore()
  };
  Rig.prototype.drawLeg=function(c,start,thigh,shin,color,skin,shoeColor,seed,front){const knee=joint(start,50,thigh+Math.PI/2),ankle=joint(knee,47,shin+Math.PI/2);capsule(c,start,knee,24*this.build,color,seed,front);c.beginPath();c.arc(knee.x,knee.y,10,0,TAU);c.fillStyle=shade(color,-8);c.fill();c.strokeStyle=INK;c.lineWidth=4;c.stroke();capsule(c,knee,ankle,19,skin,seed+2,front);shoe(c,ankle.x,ankle.y,shin,shoeColor,1.05);return ankle};
  Rig.prototype.drawArm=function(c,start,upper,lower,skin,seed,front,grip){const elbow=joint(start,42,upper+Math.PI/2),wrist=joint(elbow,38,lower+Math.PI/2);capsule(c,start,elbow,18*this.build,skin,seed,front);c.beginPath();c.arc(elbow.x,elbow.y,8,0,TAU);c.fillStyle=shade(skin,-12);c.fill();c.strokeStyle=INK;c.lineWidth=4;c.stroke();capsule(c,elbow,wrist,15,skin,seed+3,front);hand(c,wrist.x,wrist.y,lower+Math.PI/2,skin,1.05*this.build,grip);return wrist};
  Rig.prototype.drawTorso=function(c,top,bottom,b,seed,breath){const shoulder=42*b+(this.presentation==='femme'?-3:3),waist=29*b,belly=(b-1)*18,pts=[[-shoulder+wobble(seed,1),top],[shoulder+wobble(seed,2),top+2],[39*b+belly,bottom-18],[31*b+belly,bottom+5],[-31*b-belly,bottom+4],[-38*b-belly,bottom-19]];organic(c,pts,this.outfit,INK,6);c.fillStyle='rgba(0,0,0,.13)';c.beginPath();c.moveTo(4,top+5);c.quadraticCurveTo(shoulder,top+20,30*b+belly,bottom-4);c.lineTo(13,bottom);c.closePath();c.fill();if(this.top==='jacket'){c.strokeStyle=INK;c.lineWidth=4;c.beginPath();c.moveTo(0,top);c.lineTo(2,bottom);c.moveTo(-shoulder+8,top+7);c.lineTo(-8,top+27);c.lineTo(0,top+3);c.lineTo(10,top+28);c.lineTo(shoulder-7,top+7);c.stroke()}else if(this.top==='vest'){c.strokeStyle=PAPER;c.lineWidth=7;c.beginPath();c.moveTo(-18,top+1);c.lineTo(-8,bottom-8);c.moveTo(18,top+1);c.lineTo(8,bottom-8);c.stroke()}else if(this.top==='hoodie'){c.strokeStyle=INK;c.lineWidth=4;c.beginPath();c.arc(0,top+4,25,0,Math.PI);c.moveTo(-4,top+31);c.lineTo(1,top+43);c.lineTo(6,top+29);c.stroke()}else if(this.top==='tank'){c.strokeStyle=this.skin;c.lineWidth=9;c.beginPath();c.moveTo(-29*b,top+2);c.lineTo(-12,top+21);c.moveTo(29*b,top+2);c.lineTo(12,top+21);c.stroke()}c.strokeStyle='rgba(255,255,255,.2)';c.lineWidth=3;c.beginPath();c.moveTo(-shoulder+10,top+10);c.quadraticCurveTo(-22,top+27,-20,bottom-15);c.stroke();
    const crotch=bottom+17;if(this.bottom==='skirt')organic(c,[[-34*b,bottom-2],[34*b,bottom-1],[42*b,crotch+16],[-41*b,crotch+14]],shade(this.outfit,-14),INK,5);else{organic(c,[[-33*b,bottom-2],[33*b,bottom-1],[29*b,crotch+8],[7,crotch+6],[0,crotch-2],[-7,crotch+7],[-29*b,crotch+7]],shade('#4b5265',this.bottom==='leggings'?20:0),INK,5);if(this.bottom==='cargo'){ctxRoundRect(c,-31*b,bottom+4,19,18,4,'#626a7e');ctxRoundRect(c,12,bottom+4,19,18,4,'#626a7e')}}};
  Rig.prototype.drawNeck=function(c,y,skin,skinShade){organic(c,[[-13,y-5],[14,y-4],[17,y+22],[-14,y+22]],skin,INK,4);c.fillStyle=skinShade;c.beginPath();c.moveTo(4,y-3);c.lineTo(15,y);c.lineTo(15,y+21);c.lineTo(5,y+17);c.closePath();c.fill()};
  Rig.prototype.drawBackHair=function(c,x,y,seed){if(this.hair!=='ponytail'&&this.presentation!=='femme')return;c.save();c.translate(x,y);c.fillStyle=this.hairColor;c.strokeStyle=INK;c.lineWidth=5;c.beginPath();c.moveTo(-27,-16);c.quadraticCurveTo(-46,15,-30,47);c.quadraticCurveTo(0,62,31,45);c.quadraticCurveTo(45,10,26,-17);c.closePath();c.fill();c.stroke();if(this.hair==='ponytail'){c.beginPath();c.ellipse(38,10,17,31,.3,0,TAU);c.fill();c.stroke()}c.restore()};
  Rig.prototype.drawCartoonHead=function(c,x,y,skin,seed){
    c.save();c.translate(x,y);c.rotate((this.pose?.head||0)*.12);const b=this.build,wide=this.head==='wide'?1.16:this.head==='long'?.88:this.head==='pointy'?.95:1,high=this.head==='long'?1.18:this.head==='wide'?.9:1,rx=(44+4*(b-1))*wide,ry=48*high,asym=wobble(seed,7,7);
    // ears sit behind the face and are deliberately mismatched
    [-1,1].forEach((side,i)=>{c.beginPath();c.ellipse(side*(rx-1),2+i*2,10+i*1.5,15-i,side*.12,0,TAU);c.fillStyle=skin;c.fill();c.strokeStyle=INK;c.lineWidth=5;c.stroke();c.strokeStyle=shade(skin,-35);c.lineWidth=2;c.beginPath();c.arc(side*(rx-1),3+i*2,5,side<0?-1.2:1.8,side<0?1.3:4.5);c.stroke()});
    let pts;if(this.head==='square')pts=[[-rx,-ry*.72],[-rx*.65,-ry], [rx*.75,-ry*.93],[rx, -ry*.45],[rx*.94,ry*.62],[rx*.48,ry],[ -rx*.52,ry*.92],[-rx,ry*.45]];else if(this.head==='pointy')pts=[[-rx*.84,-ry*.75],[rx*.48,-ry],[rx,-ry*.2],[rx*.72,ry*.5],[asym,ry*1.13],[-rx*.88,ry*.55]];else pts=[[-rx*.7,-ry*.94],[rx*.46,-ry],[rx*.96,-ry*.55],[rx,ry*.38],[rx*.45,ry*.92],[-rx*.35,ry],[-rx,ry*.44],[-rx*.98,-ry*.35]];organic(c,pts,skin,INK,6);
    c.fillStyle='rgba(90,40,55,.12)';c.beginPath();c.moveTo(rx*.2,-ry*.82);c.quadraticCurveTo(rx*1.02,-ry*.4,rx*.58,ry*.76);c.quadraticCurveTo(rx*.3,ry*.94,rx*.12,ry*.75);c.closePath();c.fill();
    this.drawCartoonFace(c,rx,ry,seed);this.drawCartoonHair(c,rx,ry,seed);if(this.helmet){c.beginPath();c.arc(0,-5,rx+7,Math.PI,TAU);c.fillStyle='#78858c';c.fill();c.strokeStyle=INK;c.lineWidth=5;c.stroke()};c.restore()
  };
  Rig.prototype.faceState=function(){if(this.state==='victory')return'laughing';if(/dead|defeat/.test(this.state)||this.expression==='dead')return'unconscious';if(/heavyHit|fall|knockdown/.test(this.state))return'shocked';if(this.expression==='pain')return'hurt';if(this.expression==='fear')return'scared';if(this.expression==='angry')return'angry';if(this.expression==='smug')return'smug';if(this.state==='stunned')return'confused';return'neutral'};
  Rig.prototype.drawCartoonFace=function(c,rx,ry,seed){const state=this.faceState(),angry=state==='angry',scared=state==='scared',hurt=state==='hurt',shock=state==='shocked',dead=state==='unconscious',laugh=state==='laughing',smug=state==='smug',confused=state==='confused',eyeY=-7,look=this.look||0;let oh=scared||shock?14:hurt?6:dead?4:10;if(this.injuries?.blackEye){c.fillStyle='rgba(76,39,83,.72)';c.beginPath();c.ellipse(14,-6,16,13,-.2,0,TAU);c.fill()}eye(c,-15+wobble(seed,12,2),eyeY,10,oh,look,this.eyeColor,angry?.12:hurt?-.16:confused?.15:0,this.blink);eye(c,14+wobble(seed,13,2),eyeY-1,9,oh*(scared?1.12:.92),look,this.eyeColor,angry?-.12:hurt?.19:confused?-.12:0,this.blink);
    c.strokeStyle=INK;c.lineWidth=5;c.lineCap='round';c.beginPath();if(dead){c.moveTo(-24,-21);c.lineTo(-8,-13);c.moveTo(-8,-21);c.lineTo(-24,-13);c.moveTo(7,-20);c.lineTo(23,-13);c.moveTo(23,-21);c.lineTo(7,-13)}else if(angry){c.moveTo(-26,-23);c.lineTo(-7,-17);c.moveTo(7,-17);c.lineTo(25,-24)}else if(scared){c.moveTo(-25,-25);c.quadraticCurveTo(-16,-32,-7,-25);c.moveTo(6,-25);c.quadraticCurveTo(15,-33,24,-24)}else if(confused){c.moveTo(-25,-24);c.lineTo(-8,-27);c.moveTo(7,-16);c.lineTo(24,-21)}else{c.moveTo(-24,-23);c.quadraticCurveTo(-16,-26,-7,-23);c.moveTo(7,-23);c.quadraticCurveTo(15,-25,24,-22)}c.stroke();
    // a proper protruding, asymmetrical nose rather than a dot
    c.beginPath();const nose=this.head==='long'?15:this.head==='wide'?10:12;c.moveTo(-1,-5);c.quadraticCurveTo(4,5,nose,8);c.quadraticCurveTo(nose+4,13,4,15);c.quadraticCurveTo(-2,14,-4,11);c.stroke();c.fillStyle=shade(this.skin,-28);c.beginPath();c.arc(nose*.58,10,2,0,TAU);c.fill();
    c.beginPath();if(dead){c.moveTo(-11,29);c.lineTo(11,30)}else if(laugh){c.moveTo(-18,24);c.quadraticCurveTo(0,47,20,21);c.quadraticCurveTo(0,32,-18,24);c.fillStyle='#5a2533';c.fill()}else if(shock||scared){c.ellipse(2,29,8,12,0,0,TAU);c.fillStyle='#5a2533';c.fill()}else if(hurt){c.moveTo(-14,33);c.quadraticCurveTo(-2,17,15,31)}else if(angry){c.moveTo(-16,28);c.quadraticCurveTo(1,39,17,23)}else if(smug){c.moveTo(-16,25);c.quadraticCurveTo(3,39,18,19)}else if(confused){c.moveTo(-14,29);c.quadraticCurveTo(-2,21,15,29)}else{c.moveTo(-12,27);c.quadraticCurveTo(0,31,13,26)}c.stroke();if(laugh){c.fillStyle=PAPER;c.fillRect(-8,27,18,5);if(this.injuries?.missingTooth){c.fillStyle='#5a2533';c.fillRect(0,27,6,6)}}
    if(this.face==='stubble'){c.fillStyle='#4a3437';for(let i=0;i<17;i++){const px=-20+(i%6)*8,py=22+Math.floor(i/6)*7;c.beginPath();c.arc(px,py,1.1,0,TAU);c.fill()}}else if(this.face==='mustache')organic(c,[[-2,20],[-22,16],[-14,28],[0,23],[14,28],[22,15],[2,20]],this.hairColor,INK,2);else if(this.face==='beard')organic(c,[[-27,18],[-20,43],[1,54],[22,41],[27,16],[10,28],[0,25],[-11,29]],this.hairColor,INK,3);else if(this.face==='scar'){c.strokeStyle='#9b3d4b';c.lineWidth=3;c.beginPath();c.moveTo(18,-15);c.lineTo(9,1);c.lineTo(18,17);c.stroke()}
    if(this.accessory==='glasses'){c.strokeStyle=INK;c.lineWidth=4;c.beginPath();c.ellipse(-15,-7,14,12,0,0,TAU);c.ellipse(14,-8,13,11,0,0,TAU);c.moveTo(-1,-7);c.lineTo(2,-8);c.stroke()}else if(this.accessory==='eyepatch'){c.fillStyle=INK;c.beginPath();c.ellipse(14,-8,13,10,-.1,0,TAU);c.fill();c.strokeStyle=INK;c.lineWidth=3;c.beginPath();c.moveTo(-rx+4,-24);c.lineTo(rx-2,-6);c.stroke()}else if(this.accessory==='headband'){c.strokeStyle='#e8587e';c.lineWidth=8;c.beginPath();c.moveTo(-rx+2,-29);c.quadraticCurveTo(0,-24,rx-2,-30);c.stroke()}
  };
  Rig.prototype.drawCartoonHair=function(c,rx,ry,seed){if(this.hair==='bald')return;const col=this.hairColor;c.fillStyle=col;c.strokeStyle=INK;c.lineWidth=5;c.lineJoin='round';if(this.hair==='curly'){for(let i=-3;i<=3;i++){c.beginPath();c.arc(i*13,-ry+3-Math.abs(i)*2,15+(i%2),0,TAU);c.fill();c.stroke()}}else if(this.hair==='mohawk')organic(c,[[-16,-ry+9],[-12,-ry-26],[-3,-ry-11],[7,-ry-34],[17,-ry+8]],col,INK,5);else if(this.hair==='slick')organic(c,[[-rx+3,-ry+18],[-rx*.35,-ry-13],[rx*.3,-ry-18],[rx,-ry+9],[rx*.65,-ry+22],[-rx*.55,-ry+24]],col,INK,5);else if(this.hair==='spikes'){const pts=[[-rx+3,-ry+20]];for(let i=0;i<9;i++)pts.push([-rx+i*rx/4,-ry-(i%2?28:8)+wobble(seed,i,5)]);pts.push([rx-2,-ry+20]);organic(c,pts,col,INK,5)}else if(this.hair==='ponytail')organic(c,[[-rx+2,-ry+17],[-rx*.55,-ry-9],[0,-ry-15],[rx*.68,-ry-7],[rx,-ry+15],[rx*.45,-ry+24],[-rx*.55,-ry+25]],col,INK,5);else{const pts=[[-rx+3,-ry+20]];for(let i=0;i<8;i++)pts.push([-rx+i*rx/3.5,-ry-(i%2?15:2)+wobble(seed,i,4)]);pts.push([rx-3,-ry+20]);organic(c,pts,col,INK,5)}};
  Rig.prototype.drawInkSmear=function(c){c.save();c.globalAlpha=this.smear*.65;c.strokeStyle='#f6d768';c.lineCap='round';const kick=this.smearKind.includes('kick'),head=this.smearKind.includes('Head'),base=kick?(head?-128:-77):(head?-172:-119);for(let i=0;i<4;i++){c.lineWidth=11-i*2;c.beginPath();c.moveTo(20,base+i*9);c.quadraticCurveTo(75,base-20+i*5,135+i*9,base-2+i*3);c.stroke()}c.restore()};
  Rig.prototype.drawInjuries=function(c){const i=this.injuries||{};if(this.mutationGlow){c.save();c.globalAlpha=.24+.1*Math.sin(performance.now()/90);c.strokeStyle='#f3d13b';c.lineWidth=10;c.beginPath();c.ellipse(0,-112,64*this.build,112,0,0,TAU);c.stroke();c.restore()}if(i.bandage){c.fillStyle=PAPER;c.strokeStyle=INK;c.lineWidth=3;c.fillRect(-30,-111,60,14);c.strokeRect(-30,-111,60,14)}if(i.torn){c.strokeStyle=INK;c.lineWidth=3;c.beginPath();c.moveTo(-27,-101);c.lineTo(-12,-90);c.lineTo(0,-105);c.lineTo(17,-91);c.stroke()}};

  // Illustrated arena painter. It is cached by the existing renderer, so detail is paid for once per venue/resize.
  function paintTexture(c,w,h,seed,color='rgba(40,20,35,.11)'){c.save();c.fillStyle=color;for(let i=0;i<90;i++){const x=(Math.sin(seed+i*23.1)*.5+.5)*w,y=(Math.sin(seed*2+i*61.3)*.5+.5)*h,r=1+(i%5);c.beginPath();c.ellipse(x,y,r*2,r,.2,0,TAU);c.fill()}c.restore()}
  function sign(c,x,y,w,h,title,sub){c.save();c.translate(x,y);c.rotate(-.015);organic(c,[[0,3],[w,-2],[w-3,h],[4,h+2]],PAPER,INK,5);c.fillStyle=INK;c.textAlign='center';c.font='30px Impact';c.fillText(title,w/2,34);c.font='700 11px Space Mono';c.fillText(sub,w/2,54);c.restore()}
  function crack(c,x,y,s=1){c.strokeStyle='rgba(45,31,38,.38)';c.lineWidth=3;c.beginPath();c.moveTo(x,y);c.lineTo(x+15*s,y+9*s);c.lineTo(x+7*s,y+24*s);c.moveTo(x+15*s,y+9*s);c.lineTo(x+31*s,y+2*s);c.lineTo(x+38*s,y+16*s);c.stroke()}
  Game.prototype.background=function(c,w,h){const id=this.scene?.id||'backyard',grad=c.createLinearGradient(0,0,0,330);if(id==='office'){grad.addColorStop(0,'#9aa3a2');grad.addColorStop(1,'#c5c4b9')}else if(id==='buffet'){grad.addColorStop(0,'#6f3f43');grad.addColorStop(1,'#bf7657')}else if(id==='wedding'){grad.addColorStop(0,'#c68da5');grad.addColorStop(1,'#efd2d7')}else{grad.addColorStop(0,'#5aa9bb');grad.addColorStop(1,'#c7dba5')}c.fillStyle=grad;c.fillRect(0,0,w,h);
    if(id==='backyard'){c.fillStyle='#77514b';organic(c,[[24,306],[34,101],[168,39],[310,105],[316,308]],'#9d5c4d',INK,7);organic(c,[[19,106],[166,31],[323,108]],'#5a3540',INK,8);ctxRoundRect(c,55,151,98,75,3,'#c8b278');c.fillStyle='#44718a';c.fillRect(70,163,68,49);for(let x=337;x<w;x+=116){organic(c,[[x,205],[x+111,203],[x+108,307],[x+2,307]],x%232?'#c5b786':'#bbaa77',INK,4)}c.strokeStyle='#3b2e34';c.lineWidth=4;c.beginPath();c.moveTo(340,119);c.quadraticCurveTo(650,156,975,112);c.stroke();['#e65f78','#f2d351','#6acdb0','#728cdb','#a85fd1'].forEach((col,i)=>organic(c,[[400+i*125,124],[480+i*125,130],[470+i*125,183],[410+i*125,177]],col,INK,3));c.fillStyle='rgba(50,70,45,.5)';for(let x=0;x<w;x+=83){c.beginPath();c.arc(x,296,48,Math.PI,TAU);c.fill()}}
    else if(id==='office'){c.fillStyle='#c7c3b8';c.fillRect(0,0,w,310);for(let x=45;x<w;x+=245){organic(c,[[x,27],[x+181,24],[x+176,58],[x+3,61]],'#e9ecd8',INK,3);c.fillStyle='rgba(255,248,190,.32)';c.fillRect(x+9,35,158,15)}for(let x=0;x<w;x+=156){organic(c,[[x+4,118],[x+151,112],[x+146,303],[x+8,307]],x%312?'#657b7d':'#71888a',INK,5);c.fillStyle='#29383d';c.fillRect(x+27,157,73,44);c.fillStyle='#bbbdb7';c.fillRect(x+49,201,43,55)}sign(c,895,67,305,63,'TEAMWORK','because surveillance is expensive');crack(c,330,72,1.2);crack(c,748,189,.8)}
    else if(id==='buffet'){c.fillStyle='#d6a25f';c.fillRect(0,204,w,108);for(let x=17;x<w;x+=190){sign(c,x,86,160,75,['MEAT?','SOUP-ish','HOT FOOD','DESSERT'][Math.floor(x/190)%4],'seconds since fresh: unknown')}c.fillStyle='#703f37';c.fillRect(0,276,w,35);for(let x=0;x<w;x+=165){c.strokeStyle='#e3c785';c.lineWidth=6;c.beginPath();c.moveTo(x,207);c.lineTo(x+70,165);c.lineTo(x+136,207);c.stroke();c.fillStyle=pick(['#b84b48','#677f54','#cc8c3f']);c.fillRect(x+18,210,118,34)}c.fillStyle='rgba(78,37,31,.28)';for(let i=0;i<12;i++){c.beginPath();c.ellipse(55+i*111,294,25,8,.1,0,TAU);c.fill()}}
    else if(id==='wedding'){for(let x=-40;x<w;x+=165){c.fillStyle=x%330?'#f0c6d2':'#f7ded8';c.beginPath();c.moveTo(x,0);c.quadraticCurveTo(x+82,198,x+165,0);c.lineTo(x+165,308);c.lineTo(x,308);c.fill();c.strokeStyle='rgba(80,45,70,.24)';c.lineWidth=3;c.stroke()}c.strokeStyle='#5f435b';c.lineWidth=5;c.beginPath();c.moveTo(0,76);c.quadraticCurveTo(640,140,1280,68);c.stroke();for(let x=25;x<w;x+=72){c.beginPath();c.arc(x,80+Math.sin(x)*18,7,0,TAU);c.fillStyle='#f6dc72';c.fill();c.stroke()}sign(c,455,141,370,68,'TRUE-ish LOVE','refunds unavailable after impact');for(let i=0;i<8;i++){c.fillStyle=pick(['#fff0e8','#f05d8b','#5cd6b3']);c.beginPath();c.arc(230+i*120,281,11,0,TAU);c.fill()}}
    else{c.fillStyle='#64a94f';c.fillRect(0,244,w,66);organic(c,[[42,281],[53,101],[286,93],[307,280]],'#8f5bc2',INK,7);for(let x=73;x<285;x+=52)organic(c,[[x,106],[x+35,88],[x+43,164],[x-3,166]],pick(['#e85d81','#5e8de6','#f3d13b']),INK,4);for(let i=0;i<15;i++){const x=332+i*67,y=56+Math.sin(i*1.7)*27;c.strokeStyle='rgba(255,255,255,.8)';c.lineWidth=2;c.beginPath();c.moveTo(x,y+13);c.lineTo(x,178);c.stroke();c.beginPath();c.arc(x,y,14,0,TAU);c.fillStyle=pick(['#ef5e80','#5cd6b3','#f3d13b','#6d86dc']);c.fill();c.strokeStyle=INK;c.lineWidth=3;c.stroke()}sign(c,505,180,420,67,'HAPPY BIRTHDAY','please ignore the combat waiver')}
    const floor=id==='office'?'#787d7e':id==='wedding'?'#c99ea8':id==='buffet'?'#956040':'#bd8b66';c.fillStyle=floor;c.fillRect(0,308,w,h-308);c.strokeStyle=shade(floor,-28);c.lineWidth=3;for(let y=340;y<h;y+=47){c.beginPath();c.moveTo(0,y);c.lineTo(w,y+3*Math.sin(y));c.stroke()}for(let x=-80;x<w;x+=100){c.beginPath();c.moveTo(x,308);c.lineTo(x-75,h);c.stroke()}for(let i=0;i<16;i++){const x=(i*89+43)%w,y=335+(i*67)%(h-350);c.fillStyle='rgba(80,45,45,.16)';c.beginPath();c.ellipse(x,y,18+i%4*5,5+i%3,.2,0,TAU);c.fill()}crack(c,210,407,1);crack(c,1030,471,.9);paintTexture(c,w,h,hash(id));sign(c,365,27,550,76,`${this.scene.icon} ${this.scene.name}`,`LEVELS ${LB.SCENES.indexOf(this.scene)*5+1}–${LB.SCENES.indexOf(this.scene)*5+5} • ${this.scene.subtitle}`)};

  const BEHAVIORS=['cheer','laugh','boo','wince','film','point','talk','lookaway','duck'];
  const oldSpawn=Game.prototype.spawnRound;
  Game.prototype.spawnRound=function(){oldSpawn.call(this);this.visualFx=[];this.spectators.forEach((s,i)=>{s.behavior=pick(BEHAVIORS);s.headShape=pick(['round','square','long','wide','pointy']);s.nose=pick(['button','hook','long','wide']);s.jaw=pick(['soft','square','pointy']);s.shoeColor=pick(['#272431','#f0e5cf','#4e6f83','#8a354c']);s.visualSeed=hash(`${s.hair}|${s.shirt}|${i}|${s.role}`)})};
  Game.prototype.drawSpectator=function(c,s){c.save();const hype=Math.max(Math.abs(this.player.popularity),Math.abs(this.enemy.popularity))/100,near=Math.abs(this.player.rig.x-s.x)<125||Math.abs(this.enemy.rig.x-s.x)<125,wave=Math.sin(this.time*(4+hype*4)+s.phase),behavior=near?'duck':s.behavior,bounce=s.down?0:behavior==='cheer'?Math.abs(wave)*(4+hype*6):Math.abs(wave)*1.5,flight=s.down&&s.hitT<1?-Math.sin(s.hitT*Math.PI)*92:0;c.translate(s.x,s.y-bounce+flight);if(s.down)c.rotate(s.rot);c.scale(s.scale,s.scale);const skin=s.skin,seed=s.visualSeed||1,hip={x:0,y:70};let crouch=behavior==='duck'?17:0;
    const legL=joint({x:-11*s.build,y:70+crouch},32,1.52+wave*.08),legR=joint({x:11*s.build,y:70+crouch},32,1.62-wave*.08);capsule(c,{x:-11*s.build,y:70+crouch},legL,10,s.pants,seed,false);capsule(c,{x:11*s.build,y:70+crouch},legR,10,shade(s.pants,-8),seed+1,true);shoe(c,legL.x,legL.y,0,s.shoeColor,.62);shoe(c,legR.x,legR.y,0,s.shoeColor,.62);
    let la=1.92+wave*.2,ra=1.2-wave*.2;if(behavior==='cheer'){la=-2.05+wave*.2;ra=-1.1-wave*.2}else if(behavior==='boo'){la=2.8;ra=.35}else if(behavior==='point'){la=1.8;ra=.08}else if(behavior==='film'){la=.85;ra=2.25}else if(behavior==='wince'||behavior==='duck'){la=-2.25;ra=-.9}else if(behavior==='lookaway'){la=2.1;ra=1.05}
    const sl={x:-20*s.build,y:31+crouch},sr={x:20*s.build,y:31+crouch},el=joint(sl,26,la),er=joint(sr,26,ra),hl=joint(el,23,la+.18),hr=joint(er,23,ra-.18);capsule(c,sl,el,9,skin,seed+3,false);capsule(c,el,hl,8,skin,seed+4,false);capsule(c,sr,er,9,skin,seed+5,true);capsule(c,er,hr,8,skin,seed+6,true);hand(c,hl.x,hl.y,la,skin,.58);hand(c,hr.x,hr.y,ra,skin,.58,behavior==='film');
    organic(c,[[-23*s.build,23+crouch],[22*s.build,24+crouch],[26*s.build,69+crouch],[-25*s.build,71+crouch]],s.shirt,INK,4);c.fillStyle='rgba(0,0,0,.13)';c.beginPath();c.moveTo(2,27+crouch);c.lineTo(22*s.build,27+crouch);c.lineTo(23*s.build,66+crouch);c.lineTo(8,67+crouch);c.closePath();c.fill();if(s.pattern==='stripe'){c.strokeStyle=PAPER;c.lineWidth=5;c.beginPath();c.moveTo(-20,47+crouch);c.lineTo(22,46+crouch);c.stroke()}else if(s.pattern==='badge'){c.beginPath();c.arc(10,39+crouch,5,0,TAU);c.fillStyle='#f3d13b';c.fill();c.strokeStyle=INK;c.lineWidth=2;c.stroke()}
    this.drawMiniHead(c,s,seed,behavior,crouch);if(behavior==='film'){c.save();c.translate((hl.x+hr.x)/2,(hl.y+hr.y)/2);c.rotate(.08);ctxRoundRect(c,-8,-13,16,26,3,'#243c52');c.fillStyle='#89d9e1';c.fillRect(-5,-9,10,15);c.restore()}c.restore()};
  Game.prototype.drawMiniHead=function(c,s,seed,behavior,crouch){c.save();c.translate(0,crouch);const rx=s.headShape==='wide'?27:s.headShape==='long'?21:24,ry=s.headShape==='long'?29:s.headShape==='wide'?21:25;[-1,1].forEach(side=>{c.beginPath();c.ellipse(side*rx,0,6,9,0,0,TAU);c.fillStyle=s.skin;c.fill();c.strokeStyle=INK;c.lineWidth=3;c.stroke()});const pts=s.headShape==='square'?[[-rx,-18],[rx,-20],[rx,17],[16,ry],[-17,ry],[-rx,16]]:s.headShape==='pointy'?[[-rx,-18],[rx*.7,-ry],[rx,8],[0,ry+8],[-rx,9]]:[[-rx*.75,-ry],[rx*.55,-ry],[rx,-12],[rx*.9,16],[10,ry],[-14,ry],[-rx,13],[-rx,-12]];organic(c,pts,s.skin,INK,4);const fear=behavior==='wince'||behavior==='duck',laugh=behavior==='laugh',lookaway=behavior==='lookaway';eye(c,-8,-3,5,fear?8:5,lookaway?-1:0,'#4b596b',0,0);eye(c,8,-4,5,fear?8:5,lookaway?-1:0,'#4b596b',0,0);c.strokeStyle=INK;c.lineWidth=3;c.beginPath();c.moveTo(-2,-1);c.quadraticCurveTo(3,5,7,7);c.stroke();c.beginPath();if(fear)c.ellipse(0,13,4,7,0,0,TAU);else if(laugh){c.moveTo(-8,12);c.quadraticCurveTo(0,25,9,11)}else if(behavior==='boo'){c.moveTo(-8,18);c.quadraticCurveTo(0,7,9,18)}else{c.moveTo(-7,14);c.quadraticCurveTo(1,18,8,13)}c.stroke();this.drawMiniHair(c,s,rx,ry);c.restore()};
  Game.prototype.drawMiniHair=function(c,s,rx,ry){if(s.hair==='bald')return;const col=s.hairColor;if(s.hair==='curly'){[-2,-1,0,1,2].forEach(i=>{c.beginPath();c.arc(i*9,-ry+2-Math.abs(i),9,0,TAU);c.fillStyle=col;c.fill();c.strokeStyle=INK;c.lineWidth=2;c.stroke()})}else if(s.hair==='mohawk')organic(c,[[-9,-ry+5],[-5,-ry-16],[1,-ry-7],[7,-ry-20],[11,-ry+5]],col,INK,3);else if(s.hair==='spikes')organic(c,[[-rx+2,-ry+9],[-16,-ry-12],[-8,-ry-3],[0,-ry-18],[8,-ry-4],[17,-ry-13],[rx,-ry+9]],col,INK,3);else organic(c,[[-rx+2,-ry+10],[-rx*.5,-ry-7],[0,-ry-10],[rx*.55,-ry-5],[rx,-ry+10],[rx*.45,-ry+17],[-rx*.55,-ry+17]],col,INK,3)};

  class VisualFx{constructor(x,y,type,color){Object.assign(this,{x,y,type,color,life:1,vx:rnd(-70,70),vy:rnd(-130,-45),r:rnd(7,15),rot:rnd(0,TAU)})}update(dt){this.life-=dt*(this.type==='dust'?.85:1.45);this.x+=this.vx*dt;this.y+=this.vy*dt;this.vy+=this.type==='sweat'?220*dt:35*dt;this.rot+=dt*4}draw(c){c.save();c.globalAlpha=clamp(this.life,0,1);c.translate(this.x,this.y);c.rotate(this.rot);if(this.type==='star'){c.fillStyle=this.color;c.strokeStyle=INK;c.lineWidth=3;c.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?this.r*.42:this.r;c.lineTo(Math.cos(a)*r,Math.sin(a)*r)}c.closePath();c.fill();c.stroke()}else if(this.type==='sweat'){c.fillStyle='#80d8e5';c.strokeStyle=INK;c.lineWidth=2;c.beginPath();c.moveTo(0,-this.r);c.quadraticCurveTo(this.r,this.r,0,this.r);c.quadraticCurveTo(-this.r,this.r,0,-this.r);c.fill();c.stroke()}else{c.fillStyle=this.color;c.beginPath();c.arc(0,0,this.r*(1.5-this.life*.5),0,TAU);c.fill()}c.restore()}};
  const oldUpdate=Game.prototype.update;
  Game.prototype.update=function(dt){oldUpdate.call(this,dt);this.visualFx=this.visualFx||[];this.visualFx.forEach(x=>x.update(dt));this.visualFx=this.visualFx.filter(x=>x.life>0);if(this.player&&this.enemy){this.player.rig.lookTarget=.55;this.enemy.rig.lookTarget=.55}};
  const oldUpdateFighter=Game.prototype.updateFighter;
  Game.prototype.updateFighter=function(f,o,dt){if(this.training){f.rig.update(dt);return}oldUpdateFighter.call(this,f,o,dt)};
  const oldHit=Game.prototype.hit;
  Game.prototype.hit=function(v,dmg,kb,attacker,crit,blocked){oldHit.call(this,v,dmg,kb,attacker,crit,blocked);this.visualFx=this.visualFx||[];const x=v.rig.x,y=v.rig.y-(attacker.lastTargetZone==='head'?180:115),perf=this.qualityMode==='PERFORMANCE',count=blocked?2:crit?(perf?7:12):(perf?4:7);for(let i=0;i<count;i++)this.visualFx.push(new VisualFx(x+rnd(-20,20),y+rnd(-15,15),i%3===0?'sweat':'star',pick(['#f3d13b','#f05d8b','#73c7ff','#f5eedc'])));for(let i=0;i<(perf?2:5);i++)this.visualFx.push(new VisualFx(v.rig.x+rnd(-28,28),this.floor-rnd(0,18),'dust','rgba(235,211,174,.55)'));if(this.visualFx.length>(perf?42:80))this.visualFx.splice(0,this.visualFx.length-(perf?42:80));if(!v.dead&&(dmg>20||kb>20))v.rig.setState('heavyHit',.13)};
  const oldKill=Game.prototype.kill;
  Game.prototype.kill=function(v,killer,dmg,crit){oldKill.call(this,v,killer,dmg,crit);if(!killer.dead)killer.rig.setState('victory',.28)};
  const oldEnvironment=Game.prototype.useEnvironment;
  Game.prototype.useEnvironment=function(f,o){f.rig.setState('interact',.2);oldEnvironment.call(this,f,o)};
  const oldDraw=Game.prototype.draw;
  Game.prototype.draw=function(){oldDraw.call(this);const c=this.ctx;c.save();(this.visualFx||[]).forEach(x=>x.draw(c));c.restore()};
  Game.prototype.foreground=function(c,w,h){const lip=this.floor+57;c.fillStyle='#281b29';c.fillRect(0,lip,w,h-lip);c.strokeStyle=INK;c.lineWidth=7;c.beginPath();c.moveTo(0,lip);c.quadraticCurveTo(w*.45,lip+3,w,lip-2);c.stroke();c.fillStyle='#f3d13b';for(let x=-20;x<w;x+=132){c.save();c.translate(x,lip+18);c.rotate(-.18);organic(c,[[0,0],[75,-2],[73,12],[2,14]],'#f3d13b',INK,2);c.restore()}const sway=Math.sin(this.time*1.8);c.save();c.globalAlpha=.5;c.fillStyle=INK;c.beginPath();c.arc(-17,lip+47,61,0,TAU);c.fill();c.beginPath();c.arc(w+18,lip+54,68,0,TAU);c.fill();c.strokeStyle=INK;c.lineWidth=18;c.lineCap='round';c.beginPath();c.moveTo(22,lip+39);c.lineTo(42+sway*8,lip-12);c.moveTo(w-24,lip+46);c.lineTo(w-47-sway*7,lip-5);c.stroke();c.restore();if(this.scene?.id==='birthday'){for(let i=0;i<3;i++){const x=80+i*540+Math.sin(this.time*.7+i)*25,y=188+Math.sin(this.time*1.1+i)*13;c.globalAlpha=.28;c.beginPath();c.arc(x,y,18,0,TAU);c.fillStyle=['#f05d8b','#5cd6b3','#f3d13b'][i];c.fill();c.globalAlpha=1}}};
})();
